Class {
	#name : 'ChatPharoToolTestClientStub',
	#superclass : 'Object',
	#category : 'AI-ChatPharo-Tests-Env',
	#package : 'AI-ChatPharo-Tests',
	#tag : 'Env'
}

{ #category : 'adding' }
ChatPharoToolTestClientStub >> addPath: segments [

    ^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> addPathSegment: aSegment [

    ^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> entity: anEntity [

    ^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> get [

    ^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> post [

    ^ self

]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> response [

    ^ ChatPharoToolTestResponseStub new
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> timeout: seconds [

    ^ self
]
