name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        smalltalk: [ Pharo64-13, Pharo64-12 ]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }}

    steps:
      - uses: actions/checkout@v4

      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15

  gitleaks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Gitleaks Scan

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to resolve commit ranges properly

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: detect --source=. --report-path=gitleaks-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
