name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        smalltalk: [ Pharo64-14, Pharo64-13, Pharo64-12, Pharo64-11, Moose64-13, Moose64-12, Moose64-11 ]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15

  sync-wiki:
    needs: build  # This makes sure all matrix jobs must pass first
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout Pharo Wiki repository
        uses: actions/checkout@v4
        with:
          repository: 'omarabedelkader/ChatPharo.wiki'
          path: wiki-repo

      - name: Copy wiki file to wiki repository
        run: |
          cp ../../ChatPharo/ChatPharo/doc/ChatPharo-Wiki.md wiki-repo/ChatPharo-Wiki.md

      - name: Commit and push changes
        run: |
          cd wiki-repo
          git add ChatPharo-Wiki.md
          git commit -m "Update wiki from project repo [automated]" || echo "No changes to commit"
          git push